first version
GolosChain/sitemap-service pull request #1
Opened 2018-12-04 17:02 UTC by Bacher

2018-12-04 17:31 UTC, Format-X22 requested changes

2018-12-04 17:31 UTC, Format-X22 commented on scripts/get_blockchain_info.js
> +    return;
?

2018-12-04 17:31 UTC, Format-X22 commented on server/Main.mjs
> +        this._state = new StateManager();
Пропуск строки бы между объявлениями и присваиваниями.

2018-12-04 17:31 UTC, Format-X22 commented on server/Main.js
> +        const alreadySome = await DayInfo.findOne();
countDocuments

2018-12-04 17:31 UTC, Format-X22 commented on server/Main.js
> +        } catch (err) {}
Уточнить бы почему не ловим и ничего не делаем.

2018-12-04 17:31 UTC, Format-X22 commented on server/Main.js
> +            console.log('Initial sync started');
Logger

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +        const today = new Date().toJSON().substr(0, 10);
moment модуль

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +            const date = current.toJSON().substr(0, 10);
moment модуль

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +            current.setDate(current.getDate() + 1);
moment модуль

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +        const query = Post.find(
В одну строку бы.

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +        const posts = await query.exec();
Просто await перед find

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +        const WEEK_AGO = Date.now() - 7 * 24 * 60 * 60 * 1000;
moment модуль

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +    async _syncDate(date) {
Очень длинный метод.

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +        const daysInfo = await DayInfo.find({})
await и exec одновременно - странно

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +        const xmlSiteMapList = [];
Не выест ли памяти сильно?

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/SiteMapGenerator.js
> +    return date.toJSON().replace('Z', '+00:00');
moment модуль

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/StateManager.js
> +        this._state.save();
await не забыт?

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/StateManager.js
> +        const timestamp = new Date(ts.endsWith('Z') ? ts : ts + 'Z');
moment модуль

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/StateManager.js
> +        for (let tx of block.transactions) {
Есть итератор по транзакциям и всем таким, утилита Block

2018-12-04 17:31 UTC, Format-X22 commented on server/helpers/StateManager.js
> +            const date = timestamp.toJSON().substr(0, 10);
moment модуль

2018-12-04 17:31 UTC, Format-X22 commented on server/index.js
> +const core = require('gls-core-service');
defaultStarter

2018-12-04 17:31 UTC, Format-X22 commented on server/models/Post.js
> +    {
Точно все индексы нужны?

2018-12-04 17:31 UTC, Format-X22 commented on server/services/DumpLoader.js
> +        if (!somePost) {
Инвертнуть нужно.

2018-12-04 17:31 UTC, Format-X22 commented on server/services/DumpLoader.js
> +            const initialData = JSON.parse(initialDataJSON);
Пропуск строки лишним выглядит.

2018-12-05 08:31 UTC, bacher commented on server/models/Post.js
> +    {
Все используются.

2018-12-05 08:31 UTC, bacher commented on server/services/DumpLoader.js
> +        if (!somePost) {
Плохо будет, придется два раза `this.done()` вызывать.

2018-12-05 09:58 UTC, Bacher commented on server/helpers/SiteMapGenerator.js
> +        const xmlSiteMapList = [];
Там меньше чем 1000 записей. 1 запись за 1 день. В любом случае они все будут в памяти, так как генерация XML не потоковая.

2018-12-05 10:02 UTC, Bacher commented on server/services/DumpLoader.js
> +            const initialData = JSON.parse(initialDataJSON);
Убрал

2018-12-05 10:37 UTC, Bacher commented on server/helpers/SiteMapGenerator.js
> +    async _syncDate(date) {
Уменьшен, так нормально?

2018-12-05 10:52 UTC, Format-X22 approved these changes

2018-12-05 14:39 UTC, merged