Develop
GolosChain/sitemap-service pull request #7
Opened 2019-09-04 10:21 UTC by Bacher

2019-09-04 10:38 UTC, IvanBlacky requested changes

2019-09-04 10:38 UTC, IvanBlacky commented on .eslintrc
> +{
Мы на бэке не используем eslint, только prettier

2019-09-04 10:38 UTC, IvanBlacky commented on Dockerfile
> +FROM node:10 as builder
node:10-alpine наш новый base image

2019-09-04 10:38 UTC, IvanBlacky commented on Dockerfile
> +FROM node:10 as builder
зачем `as builder`?

2019-09-04 10:38 UTC, IvanBlacky commented on docker-compose.dev.yml
> +services:
еще нужен mongo-exporter

2019-09-04 10:38 UTC, IvanBlacky commented on docker-compose.yml
> +    image: cyberway/sitemap-service:0.1.0
:+1: 
:heart_eyes:

2019-09-04 10:38 UTC, IvanBlacky commented on package.json
> +    "test": "eslint src/**/*.js"
не думаю, что привязывать eslint на скрипт test -- хорошая идея

2019-09-04 10:38 UTC, IvanBlacky commented on src/data/env.js
> +    ...core.data.env,
Это излишне

2019-09-04 10:38 UTC, IvanBlacky commented on src/index.js
> +const gls = require('gls-core-service');
Есть уже устоявшаяся форома записи старта в этом файле:
```javascript
require('gls-core-service').utils.defaultStarter(require('./Main'));
```

2019-09-04 10:38 UTC, IvanBlacky commented on src/models/Date.js
> +        lastUpdateAt: {
Не очень понятно, зачем это, если есть системное `updatedAt`?

2019-09-04 10:38 UTC, IvanBlacky commented on src/models/Post.js
> +        updatedAt: {
Коллизия с системным полем. Лучше так не делать

2019-09-04 10:38 UTC, IvanBlacky commented on src/utils/time.js
> +function wait(ms) {
Есть замечательная утилита [then-sleep](https://www.npmjs.com/package/then-sleep), которую мы используем во всех наших сервисах. Не нужно изобретать велосипед :)

2019-09-04 10:47 UTC, beautyfree approved these changes

2019-09-04 10:50 UTC, Bacher commented on src/data/env.js
> +    ...core.data.env,
Не, это патерн расширения env'ов, в некоторых местах нужно енвы которые приходят из gls-core-service. Конкретно в данный момент времени они не используются, но это вопрос времени.

2019-09-04 10:55 UTC, Bacher commented on docker-compose.dev.yml
> +services:
Добавил, но не в `docker-compose.dev.yml` а в `docker-compose.yml`.

2019-09-04 10:55 UTC, Bacher commented on src/index.js
> +const gls = require('gls-core-service');
Согласен

2019-09-04 10:56 UTC, Bacher commented on src/models/Date.js
> +        lastUpdateAt: {
В данном случае это разные времена, lastUpdateAt это время последнего обновления постов опубликованных в этот день, а не просто время обновления записи.

2019-09-04 10:57 UTC, Bacher commented on src/models/Post.js
> +        updatedAt: {
Точняк. Хорошо что ты заметил.

2019-09-04 11:00 UTC, b1acksun approved these changes

2019-09-04 11:01 UTC, Bacher commented
@IvanBlacky Спасибо за ревью, ценно.

2019-09-04 11:16 UTC, IvanBlacky approved these changes

2019-09-04 14:12 UTC, IvanBlacky approved these changes

2021-09-03 10:25 UTC, Bacher commented
Abandoned

2021-09-03 10:25 UTC, closed without merging